# Generated by Django 3.2.7 on 2021-09-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='fechaCreacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('archivoAudio', models.FileField(blank=True, null=True, upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.album')),
            ],
        ),
    ]
